### 历史api，使用的是demo数据库
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "username":"aaa",
    "password":"123"
}

### 历史api，使用的是demo数据库
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "aaa",
    "password": "123"
}


### 查询病人1的信息
GET http://localhost:8080/api/patients/1

### 查询病人1历史病历记录
GET http://localhost:8080/api/patients/1/records

### 查询药品1信息
GET http://localhost:8080/api/medicines/1

